### ISSUE TITLE
Drizzle Box | Errors on Start

### ISSUE THREAD

**Issue by KamesCG** [truffle-box/drizzle-box#18]
Excited to checkout the power of Drizzzzzle!

Using my handy-dandy `truffle unbox` command I pulled down the `drizzle` box.

However, after attempting to launch with `npm run start` command (also the `ganache-cli` command) I get the following errors. Haven't attempted to do debug, which I will do now, but I thought it might help to just post an issue now, in case anyone else encounters the same errors.  

```
drizzle.js:26073 Error retrieving network ID:
(anonymous) @ drizzle.js:26073
drizzle.js:26074 TypeError: Cannot read property 'address' of undefined
    at http://localhost:3000/static/js/bundle.js:69576:103
From previous event:
    at new DrizzleContract (http://localhost:3000/static/js/bundle.js:69575:27)
    at Drizzle.getContracts (http://localhost:3000/static/js/bundle.js:69461:58)
    at http://localhost:3000/static/js/bundle.js:69442:17
(anonymous) @ drizzle.js:26074
drizzle.js:26073 Error retrieving network ID:
(anonymous) @ drizzle.js:26073
drizzle.js:26074 TypeError: Cannot read property 'address' of undefined
    at http://localhost:3000/static/js/bundle.js:69576:103
From previous event:
    at new DrizzleContract (http://localhost:3000/static/js/bundle.js:69575:27)
    at Drizzle.getContracts (http://localhost:3000/static/js/bundle.js:69461:58)
    at http://localhost:3000/static/js/bundle.js:69442:17
(anonymous) @ drizzle.js:26074
drizzle.js:26073 Error retrieving network ID:
(anonymous) @ drizzle.js:26073
drizzle.js:26074 TypeError: Cannot read property 'address' of undefined
    at http://localhost:3000/static/js/bundle.js:69576:103
From previous event:
    at new DrizzleContract (http://localhost:3000/static/js/bundle.js:69575:27)
    at Drizzle.getContracts (http://localhost:3000/static/js/bundle.js:69461:58)
    at http://localhost:3000/static/js/bundle.js:69442:17
```

**Comment by xtellurian** [comment]
Looks like you need to deploy your contracts.

*While* running ganache-cli, in a separate console run:
`truffle console` - attaches to ganache
then, in the truffle console, run:
`compile`
`migrate`

**Comment by zerostatic** [comment]
I had the same errors - fixed by changing my Metamask network to: localhost:8545 (the default Ganache port)

**Comment by KamesCG** [comment]
From the master himself @DiscRiskandBisque 

```
Are you using `ganache-cli` as the development blockchain? If so, make sure it's version `6.1.0` or above.

Also, use an incognito window or disable MetaMask.

Currently Drizzle uses subscriptions to keep the store in sync by observing new block headers, making it incompatible with MetaMask. I'm adding a polling fallback in the next version to alleviate this.
```

**Comment by ColdDevil** [comment]
Okay, after 5 hours of trial&error, I found a solution. I guess it is an issue related to incompatible npm packages. This process works for me:
- open a terminal, start with an empty folder
- truffle unbox drizzle
- edit package.json and add to the dependencies section:
  - "eth-block-tracker-es5": "^2.3.2"
  - "web3": "1.0.0-beta.34"
- npm update (to install the aforementioned packages and to update drizzle and its components to the latest version)
- run in another terminal: ganache-cli -b 3
- truffle compile
- truffle migrate
- npm run start

**Comment by aaronbarnardsound** [comment]
Thanks @ColdDevil that worked for me!!

**Comment by ColdDevil** [comment]
is the value updated on a page refresh? for me it was sometimes updated immediately and sometimes only after setting another value ;)
