### ISSUE TITLE
Broken contract dep path

### ISSUE THREAD

**Issue by kumavis** [truffle-box/drizzle-box#2]
```
╭─xyz@xyzs-MacBook-Pro ~/dev/drizzle-box  ‹develop*› 
╰─$ truffle compile && truffle migrate   
Error: Could not find zeppelin-solidity/contracts/token/StandardToken.sol from any sources; imported from /Users/xyz/dev/drizzle-box/contracts/TutorialToken.sol
    at /Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:76:1
    at /Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at next (/Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/async/whilst.js:68:1)
    at /Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:64:1
    at /Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:65:1
    at /Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/async/internal/once.js:12:1
    at replenish (/Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/async/internal/eachOfLimit.js:59:1)
    at iterateeCallback (/Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/async/internal/eachOfLimit.js:49:1)
    at /Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at ReadFileContext.callback (/Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:61:1)
```

**Comment by sprice** [comment]
Just tried things out on `1.0.0` and I don't think this is an issue anymore.
