### ISSUE TITLE
TypeError: on Vanilla Install: Cannot read property 'connection' of undefined 

### ISSUE THREAD

**Issue by crazyrabbitLTC** [truffle-box/drizzle-box#54]
A vanilla install of drizzle-box crashes Ganache-cli with the message: 

"TypeError: Cannot read property 'connection' of undefined" (I'll put full error below). 

Steps to recreate: Unbox drizzle-box. In a seperate terminal, run Ganache-cli -b -3 for three second blocktimes. 

Truffle compile
Truffle migrate

Then npm run start to start application. Web site loads. (With unlocked metamask on same network). 

Attempt to use simple contract to make a transaction. Confirm transaction and ganache-cli crashes. 

Could be a Ganache Problem, but thought to post it here. First time I've had a ganache problem like this. 

Full Error: 
TypeError: Cannot read property 'connection' of undefined
    at n._updateSubscriptions (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:65:5443)
    at l.<anonymous> (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:65:3860)
    at l.emit (events.js:127:13)
    at o.<anonymous> (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:37:29971)
    at o.emit (events.js:127:13)
    at o._notificationHandler (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:95090)
    at Array.forEach (<anonymous>)
    at s.<anonymous> (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:94594)
    at s.emit (events.js:127:13)
    at s.update (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:92445)
    at s.emit (events.js:132:15)
    at s._setCurrentBlock (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:224462)
    at c.t._blockTracker.on.e (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:223066)
    at c.emit (events.js:132:15)
    at c._setCurrentBlock (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:65:7605)
    at v.emit (events.js:127:13)
    at u.parallel (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:30:161351)
    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:82510
    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:67819
    at i (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:71283)
    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:70761
    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:82490

**Comment by oldwolf** [comment]
ganache-cli got serious problem with metamask 4.12.0, metamask team has released 4.13.0 a few hours ago, update it to resolve these conflicts.
