### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by RobinReborn** [truffle-box/drizzle-box#66]
After running 

npm install -g truffle
npm install -g ganache-cli

and then

truffle unbox drizzle I get this error:

/home/robin/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:116451
    async function detectNetworkId() {
          ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by miroosama** [comment]
try `nvm use 8`

**Comment by Marker451** [comment]
> try `nvm use 8`
This works for me . Thanks

**Comment by adrianmcli** [comment]
Closed due to inactivity, and also because the box has been re-written from scratch.
